version: '3.4'

services:
  publisher_api:
    image: ${DOCKER_REGISTRY-}publisherapi
    build:
      context: .
      dockerfile: publisher_api/Dockerfile

  worker:
    image: ${DOCKER_REGISTRY-}consumerworker
    build:
      context: .
      dockerfile: consumer_worker/Dockerfile

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

 
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          MSSQL_SA_PASSWORD: "@A123456789@"
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      volumes:
        -  "C:\\My Space\\DB\\docker-compos\\data:/var/opt/mssql/data"
        -  "C:\\My Space\\DB\\docker-compos\\log:/var/opt/mssql/log"
        -  "C:\\My Space\\DB\\docker-compos\\secrets:/var/opt/mssql/secrets"
