/*
 * publisher_api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.1.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "https://localhost:5050";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/Values", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/Values`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/Values`;
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let payload = JSON.stringify(
                { 
                    "Message": "123 ",
                    "ReceiveDateTime":"2022-08-20T10:40:15"
                }
                
            );
            let request = http.post(url,payload, params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

}
